name: Build Feature & Dev Branches

on:
  push:
    branches:
      - 'mw-**'
      - 'feat/**'
      - 'dev'
      - 'next'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: DEV
    secrets: inherit
  cd:
    needs: [ ci ]
    uses: ./.github/workflows/cd.yml
    with:
      environment: DEV
    secrets: inherit
